web/router.ex
defmodule Wiki.Router do
  use Wiki.Web, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Wiki do
    pipe_through [:browser] # Use the default browser stack

    get "/", PageController, :index

    get "/game", GameController, :index
    get "/game/create", GameController, :create
    get "/game/:slug", GameController, :show
    post "/game/create", GameController, :create
    get "/game/search", GameController, :steam_search
  end

  # API's
  scope "/", Wiki do
    pipe_through [:api]

    get "/game/search_steam/:name", GameController, :search_steam
  end

  scope "/auth", Wiki do
    pipe_through :browser

    get "/", AuthController, :index
    get "/exit", AuthController, :signout

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end
end

lib/wiki/endpoint.ex
defmodule Wiki.Endpoint do
  use Phoenix.Endpoint, otp_app: :wiki

  socket "/socket", Wiki.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :wiki, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_wiki_key",
    signing_salt: "dJZSPRdE"

  plug Wiki.Router
end

lib/wiki/repo.ex
defmodule Wiki.Repo do
  use Ecto.Repo, otp_app: :wiki
end

web/models/game.ex
defmodule Wiki.Game do
  use Wiki.Web, :model

  schema "games" do
    field :name, :string
    field :description, :string
    field :release, :integer, default: 2012
    field :boxart, :string       # Should be replaced with id on S3
    field :platform, :string

    field :about, :string
    field :help, :string

    many_to_many :tags, Wiki.Tag, join_through: "games_tags"
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :description, :release, :boxart, :platform, :about, :help])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

web/models/tag.ex
defmodule Wiki.Tag do
  use Wiki.Web, :model

  schema "tags" do
    field :tag, :string

    many_to_many :games, Wiki.Game, join_through: "games_tags"
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:tag, :games])
    |> validate_required([:tag])
  end
end

web/models/user.ex
defmodule Wiki.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :coreid, :binary_id
    field :email, :string
    field :nick, :string
    field :token, :string
    field :refresh_token, :string
    field :expires, :naive_datetime

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:coreid, :email, :nick, :token, :refresh_token, :expires])
    |> validate_required([:coreid, :email, :token, :refresh_token, :expires])
    |> unique_constraint(:coreid)
  end
end

web/controllers/auth_controller.ex
defmodule Wiki.AuthController do
  use Wiki.Web, :controller
  plug Ueberauth
  alias Ueberauth.Strategy.Helpers

  def request(conn, _params) do
    conn
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate. #{inspect _fails}")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case find_or_create(auth) do
      {:ok, user} ->
        conn
        |> Wiki.Guardian.Plug.sign_in(user)
        |> put_flash(:info, "Hooray! Logged in!")
        |> redirect(to: "/")
      {:error, reason} ->
        conn
        |> put_flash(:error, "Something went wrong")
        |> redirect(to: "/")
    end

    conn
    |> put_flash(:info, "Logged in: #{inspect auth}")
    |> redirect(to: "/")
  end

  defp find_or_create(auth) do
    user = Repo.get_by(Wiki.User, coreid: auth.uid)

    case is_nil(user) do
      true -> create(auth)
      false -> {:ok, user}
    end
  end

  defp create(auth) do
    changeset = Wiki.User.changeset(%Wiki.User{
      coreid: auth.uid,
      email: auth.info.email,
      nick: auth.info.nickname,
      token: auth.credentials.token,
      refresh_token: auth.credentials.refresh_token,
      expires: NaiveDateTime.add(~N[1970-01-01 00:00:00], auth.credentials.expires_at)
    })

    case Repo.insert(changeset) do
      {:ok, user} -> {:ok, user}
      {:error, changeset} ->
        Repo.rollback(changeset)
        {:error, "Something went wrong inserting user"}
    end
  end
end

web/controllers/game_controller.ex
defmodule Wiki.GameController do
  use Wiki.Web, :controller
  alias Wiki.Game
  alias Wiki.SteamGame

  def index(conn, _params) do
    conn |> text("Here you should be able to search for games")
  end

  def show(conn, _params = %{"slug" => slug}) do
    case Repo.get(Game, from_slug slug) do
      nil -> conn |> text("Game doesnt exist")
      game ->
        conn |> render("game.html", game: game, tags: Repo.all(assoc(game, :tags)))
    end
  end

  def create(conn = %{method: "GET"}, _params) do
    changeset = Game.changeset(%Game{})
    conn
    |> render("create.html", changeset: changeset)
  end

  def search_steam(conn, _params = %{"name" => name}) do
    #query = from g in SteamGame,
    #  where: fragment("? SOUNDS LIKE ?", ^name, g.name),
    #  order_by: [asc: g.appid],
    #  limit: 7,
    #  select: map(g, [:appid, :name])

    #case Repo.all(query) do
    #  [] -> conn |> json %{"error" => "nothing found"}
    #  games -> conn |> json games
    #end


    case Elasticsearch.post(Wiki.ElasticsearchCluster, "/logstash-*/_search", %{"query" =>
                                                                            %{"multi_match" =>
                                                                               %{"query" => name,
                                                                                "fields" => ["name"]}
                                                                             }
                                                                               }) do
      {:ok, %{"hits" => hits}} -> conn |> json hits
      otherwise -> conn |> json %{"error" => "nothing found"}
    end
  end

  def create(conn = %{method: "POST"},
  _params = %{"game" => game}) do
    changeset = Game.changeset(%Game{}, game)

    if changeset.valid? do
      Repo.insert(changeset)

      conn
      |> put_flash(:info, "Created game")
      |> redirect(to: "/")
    else
      conn
      |> render("create.html", changeset: changeset)
    end
  end

  defp from_slug(slug) do
    slug |> String.split("-") |> List.last
  end

  defp random_string() do
    Ecto.UUID.generate |> binary_part(0, 8)
  end
end

web/controllers/page_controller.ex
defmodule Wiki.PageController do
  use Wiki.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/auth_view.ex
defmodule Wiki.AuthView do
  use Wiki.Web, :view
end

web/views/error_view.ex
defmodule Wiki.ErrorView do
  use Wiki.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/game_view.ex
defmodule Wiki.GameView do
  use Wiki.Web, :view
end

web/views/layout_view.ex
defmodule Wiki.LayoutView do
  use Wiki.Web, :view
end

web/views/page_view.ex
defmodule Wiki.PageView do
  use Wiki.Web, :view
end

web/templates/game/create.html.eex
<div class="container create-game">
  <h2>add a new game</h2>

  <%= form_for @changeset, game_path(@conn, :create), fn f -> %>

  <div class="form-group form-check">
    <%= checkbox f, :steam, class: "form-check-input" %>
    <label class="form-check-label" for="game_name">On steam?</label>
  </div>

  <div class="form-group">
    <label for="game_name">Name</label>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="game_description">Description</label>
     <%= textarea f, :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="game_boxart">Boxart</label>
    <%= text_input f, :boxart, class: "form-control" %>
  </div>

  <%= submit "Add!" %>
  <% end %>
</div>

<script>
  /* 
    // NON-ELASTICSEARCH
    var matcher = function() {
    return function findMatches(q, cb, a) {
      var matches, substringRegex;

      matches = [];

      $.get("/game/search_steam/" + q).done(function(data) {
        $.each(data, function(i, d) {
          matches.push(d.name);
        });

        a(matches);
      });


    };
  };

  $("#game_name").typeahead({
    hint: true,
    minLength: 2,
    highlight: true
  },
  {
    name: "games",
    source: matcher()
  }); */

  var matcher = function() {
    return function findMatches(q, cb, a) {
      var matches, substringRegex;

      matches = [];

      /*$.post("http://10.0.75.2:9200/logstash-*\/_search",
        {
          "query": {
            "multi_match": {
              "query": q,
              "fields": ["name"]
            }
          }
        }, function(data) {
        $.each(data, function(i, d) {
          matches.push(d.name);
        });

        a(matches);
      }, "json"
      );*/
      console.log($("#game_steam").is(':checked'));
        if($("#game_steam").is(':checked')) {
        $.ajax({
            url: "http://localhost:4000/game/search_steam/" + q,
            type: "GET",
            dataType: "json",
            contentType: "application/json",
        }).done(function(data) {
            $.each(data.hits, function(i, d) {
              matches.push(d._source.name);
            });

            a(matches);
        });
      };
    };
  };

  $("#game_name").typeahead({
    hint: true,
    minLength: 2,
    highlight: true,
    cache: true
  },
  {
    name: "games",
    source: matcher()
  });

  if($("#game_steam").is(':checked')) {
    $("#game_boxart").hide();
  }
  
  $("#game_steam").click(function() {
    if($("#game_steam").is(':checked')) {
      $("#game_boxart").hide();
    } else {
      $("#game_boxart").show();
    }
  });
</script>

web/templates/game/game.html.eex
<div class="game-background" style="background: url('') rgb(30, 30, 30)">
  <svg class="bg-slash-top" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
    <polygon fill="rgb(30, 30, 30)" points="0,0 100,0 0,100"/>
  </svg>

  <svg class="bg-slash-bottom" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
    <polygon fill="rgb(30, 30, 30)" points="0,100 100,0 100,100"/>
  </svg>
</div>

<div class="container">
  <div class="row game-header">
    <div class="col col-md-8 mr-auto game-info">
      <h2 style="font-weight: 100"><%= @game.name %></h2>
      <dl style="font-size: 1.25rem" class="row">
        <dt class="col-sm-3">Release</dt>
        <dd class="col-sm-8"><%= @game.release %></dd>

        <dt class="col-sm-3">Developer</dt>
        <dd class="col-sm-8">Blizzard Entertainment</dd>

        <dt class="col-sm-3">Platform</dt>
        <dd class="col-sm-8"><%= @game.platform %></dd>
      </dl>

      <!-- <%= text_to_html @game.description %> -->

      <p>
        <%= for tag <- @tags do %>
            <span class="badge badge-secondary"><%= tag.tag %></span>
        <%= end %>
      </p>
    </div>
    <div class="col-auto col-md-auto box-art-container">
      <div class="box-art" style='background-image: url("<%= @game.boxart %>")'></div>
    </div>
  </div>

  <div class="row game-body">
    <div class="col col-md-2"></div>
    <div class="col col-md-8 mr-auto game-body-main">
      <div class="container">
          <span class="float-right"><a href="#" id="editAbout">edit</a></span><h2>About</h2>
          <div id="about" >
          <%= text_to_html @game.about %>
          </div>

        <h2>How to get</h2>
        <p>
            <a href="#" class="btn btn-primary">Battle.net</a>
            <a href="#" class="btn btn-secondary">Steam</a>
        </p>

        <h2>How to run</h2>
        <%= text_to_html @game.help %>

        <!-- <h2>Similar games</h2>
        <ul class="list-inline">
          <li class="list-inline-item">World of Warcraft: Wrath of the Lich King</li>
          <li class="list-inline-item">Diablo III</li>
        </ul>-->

      </div>
    </div>

    <!--<div style="padding-left: 0; padding-right: 0;" class="col-auto col-md-4">
      <div class="game-body-extra-multiplayer">
      <h4>Upcoming events</h4>
      <ul>
        <li>Lorem ipsum</li>
        <li>More events</li>
        <li>An amazing event</li>
      </ul>
      </div>
    </div>-->
  </div>
</div>

<script>
 let editing = false;

 $("#editAbout").on("click", function() {
     if(!editing) {
         editing = true;
        $("#editAbout").text("save");
        $("#about").attr('contenteditable', "true");
     } else {
         editing = false;
         $("#editAbout").text("edit");
         $("#about").attr('contenteditable', "false");
         $.ajax();
         console.log("TODO: Save");
 }
 });
</script>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Wiki!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:200,300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans" rel="stylesheet"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.jquery.min.js" integrity="sha256-nORlj0J8ZjvGz+6rtHb2Jcc0QDASsDUNOwUkfcwoW8A=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <!--<nav class="navbar navbar-expand-md sticky-top navbar-light">-->
    <nav class="navbar navbar-expand-md navbar-light">
      <a class="navbar-brand" href="#">dgportal<sup>alpha</sup></a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link active" href="#">link1</a>
          </li>
        </ul>
        <%= if Guardian.Plug.current_resource(@conn) != nil do %>
            Logged in!
        <% else %>
            <a class="navbar-link" href="/auth/core">log in</a>
        <% end %>
      </div>
    </nav>

    <div class="container app-container">

      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <footer>
      <svg class="footer-slash" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
        <polygon fill="rgb(19, 19, 19)" points="0,100 100,0 100,100"/>
      </svg>

      <div class="content">
        <div class="row">
          <div class="col col-md-2"></div>
          <div class="col col-md-6"></div>
          <div class="col col-md-4">
            &copy; Alexander Troshin 2018 All Rights Reserved<br>
            Made with ❤ for the Dead MP Steam Games Group
          </div>
        </div>
      </div>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="container">
  <h2>Welcome to dgportal</h2>
  <a href="#">test link</a>
</div>